// MoviesV/src/components/OidcCallback.vue
///////////////////////////////////////
//                                   //
//    Author: Max Schwaibold         //
//    Date:   28.05.2020             //
//                                   //
///////////////////////////////////////

<template>
    <h1>Completing login. This may take some seconds...</h1>
</template>

<script>
    /* eslint no-console: ["error", { allow: ["log", "error"] }] */
    import { UserManager } from 'oidc-client';

    export default {
        created() {
            let store = this.$store;
            let router = this.$router;
            new UserManager({ response_mode: 'query' }).signinRedirectCallback().then(function () {
                store.dispatch('login');
                router.push('/');
            }).catch(function (e) {
                console.error(e);
            });
        },
        data() {
            return {};
        }        
    }
</script>

// MoviesA/ClientApp/src/app/oidc-callback/oidc-callback.component.ts
///////////////////////////////////////
//                                   //
//    Author: Max Schwaibold         //
//    Date:   15.04.2020             //
//                                   //
///////////////////////////////////////

import { Component } from '@angular/core';
import { UserManager } from 'oidc-client';

@Component({
  selector: 'app-oidc-callback',
  templateUrl: './oidc-callback.component.html'
})

export class OidcCallbackComponent {
  public oidc = 'Completing login. This may take some seconds...';

  constructor() {
    new UserManager({ response_mode: "query" }).signinRedirectCallback().then(function () {
      window.location.href = "/";
    }).catch(function (e) {
      console.error(e);
    });
  }
}

<!--
///////////////////////////////////////
//                                   //
//    Author: Max Schwaibold         //
//    Date:   15.04.2020             //
//                                   //
///////////////////////////////////////
-->

<h1>{{oidc}}</h1>
