// MoviesA/ClientApp/src/app/movie-details/movie-details.component.ts
///////////////////////////////////////
//                                   //
//    Author: Max Schwaibold         //
//    Date:   30.04.2020             //
//                                   //
///////////////////////////////////////

import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { MovieService } from '../movie.service';
import { Movie } from '../movie';

@Component({
  selector: 'app-movie-details',
  templateUrl: './movie-details.component.html'  
})
export class MovieDetailsComponent implements OnInit {

  public movie: Movie;

  constructor(private route: ActivatedRoute, private router: Router, private movieService: MovieService) {
  }

  ngOnInit(): void {
    this.getMovie();
  }

  getMovie(): void {
    const id = +this.route.snapshot.paramMap.get('id');
    this.movieService.getMovie(id)
      .subscribe(movie => this.movie = movie);
  }

  public saveMovie() {
    if (this.movie.id > 0) {
      this.movieService.updateMovie(this.movie).subscribe();
    }
    else {
      this.movieService.addMovie(this.movie).subscribe();
    }
  }
}

<!--
///////////////////////////////////////
//                                   //
//    Author: Max Schwaibold         //
//    Date:   30.04.2020             //
//                                   //
///////////////////////////////////////
-->

<p *ngIf="!movie"><em>Loading...</em></p>

<form *ngIf="movie">
  <div class="form-group">
    <label for="title">Title:</label>
    <input type="text" class="form-control" id="title" name="title" [(ngModel)]="movie.title" /><br>
  </div>
  <div class="form-group">
    <label for="image">Image URL:</label>
    <input type="text" class="form-control" id="image" name="image" [(ngModel)]="movie.imageUrl" /><br>
  </div>
  <div class="form-group">
    <label for="review">Review:</label>
    <textarea type="text" class="form-control" id="review" name="review" [(ngModel)]="movie.review"></textarea><br>
  </div>
  <div class="form-group">
    <label for="rating">Rating:</label>
    <input type="text" class="form-control" id="rating" name="rating" [(ngModel)]="movie.rating" /><br>
  </div>
  <button type="button" class="btn btn-primary" (click)="saveMovie()">Save</button>
</form>

// MoviesV/src/components/MovieDetails.vue
///////////////////////////////////////
//                                   //
//    Author: Max Schwaibold         //
//    Date:   28.05.2020             //
//                                   //
///////////////////////////////////////

<template>
    <div>
        <p v-if="movie == null"><em>Loading...</em></p>
        <b-form v-else @submit="save(movie)">
            <b-form-group label="Title:" label-for="title">
                <b-form-input type="text" id="title" v-model="movie.title"></b-form-input>
            </b-form-group>
            <b-form-group label="Image URL:" label-for="imageUrl">
                <b-form-input type="text" id="imageUrl" v-model="movie.imageUrl"></b-form-input>
            </b-form-group>
            <b-form-group label="Review:" label-for="review">
                <b-form-textarea id="title" v-model="movie.review"></b-form-textarea>
            </b-form-group>
            <b-form-group label="Rating:" label-for="rating">
                <b-form-input type="text" id="rating" v-model="movie.rating"></b-form-input>
            </b-form-group>
            <b-button type="submit" variant="primary">Save</b-button>
        </b-form>       
    </div>
</template>

<script>
    /* eslint no-console: ["error", { allow: ["log"] }] */
    import axios from 'axios';

    export default {
        created() {
            let id = this.$route.params.id;
            axios.get('https://localhost:44300/movies/' + id)
                .then(response => {
                    this.movie = response.data;
                }, error => {
                    console.log(error);
                });
        },
        data() {
            return {
                movie: null
            }
        },        
        methods: {
            save(movie) {
                if (movie.id > 0) {
                    axios.put('https://localhost:44300/movies', movie).then(this.$router.push('/movies'));
                } else {
                    axios.post('https://localhost:44300/movies', movie).then(this.$router.push('/movies'));
                }
            }
        }
    }
</script>
