// MoviesA/ClientApp/src/app/movies/movies.component.ts
///////////////////////////////////////
//                                   //
//    Author: Max Schwaibold         //
//    Date:   15.04.2020             //
//                                   //
///////////////////////////////////////

import { Component, Inject } from '@angular/core';
import { MovieService } from '../movie.service';
import { AuthService } from '../auth/auth.service';
import { Movie } from '../movie';

@Component({
  selector: 'app-movies',
  templateUrl: './movies.component.html'
})
export class MoviesComponent {
  public movies: Movie[];

  constructor(private movieService: MovieService, public auth: AuthService, @Inject('BASE_URL') baseUrl: string) {
    movieService.getMovies().subscribe(result => {
      this.movies = result;
    }, error => console.error(error));
  }
}



<!--
///////////////////////////////////////
//                                   //
//    Author: Max Schwaibold         //
//    Date:   15.04.2020             //
//                                   //
///////////////////////////////////////
-->

<h1 id="tableLabel">Movies seen in 2020</h1>

<p>This component demonstrates fetching data from the server.</p>

<p *ngIf="!movies"><em>Loading...</em></p>

<table class='table table-striped' aria-labelledby="tableLabel" *ngIf="movies">
  <thead>
    <tr>
      <th>Poster</th>
      <th>Review</th>
      <th>Rating</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let movie of movies">
      <td><img [src]="movie.imageUrl" [alt]="movie.title" /></td>
      <td>
        <h2>{{movie.title}}</h2>
        <div>
          {{ movie.review }}
        </div>
        <div>
          Added: {{ movie.created }}
        </div>
        <div *ngIf="movie.updated">
          Updated: {{ movie.updated }}
        </div>
        <div>
          <a class="btn btn-outline-dark" *ngIf="auth.isLoggedIn" routerLink="/movie-details/{{ movie.id }}">Edit</a>
        </div>
      </td>
      <td><span *ngIf="movie.rating">{{ movie.rating }}/10</span></td>
    </tr>
  </tbody>
</table>

// MoviesV/src/components/Movies.vue
///////////////////////////////////////
//                                   //
//    Author: Max Schwaibold         //
//    Date:   27.05.2020             //
//                                   //
///////////////////////////////////////

<template>
    <div>
        <h1 id="tabelLabel">Movies seen in 2020</h1>
        <p>This component demonstrates fetching data from the server.</p>
        <p v-if="loading"><em>Loading...</em></p>
        <table v-else class="table table-striped" aria-labelledby="tabelLabel">
            <thead>
                <tr>
                    <th>Poster</th>
                    <th>Review</th>
                    <th>Rating</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="movie in movies" :key="movie.id">
                    <td><img src="movie.imageUrl" alt="movie.title" /></td>
                    <td>
                        <h2>{{movie.title}}</h2>
                        <div>
                            {{movie.review}}
                        </div>
                        <div>
                            Added: {{movie.created}}
                        </div>
                        <div>
                            Updated: {{movie.updated}}
                        </div>
                        <div>
                            <a class="btn btn-outline-dark" href="'movie-details/' + movie.id">Edit</a>
                        </div>
                    </td>
                    <td><span>{{movie.rating}}/10</span></td>
                </tr>
                )}
            </tbody>
        </table>
    </div>
</template>

<script>
    export default {
        data() {
            return {
                loading: false,
                movies: [{ title: "Star Wars IX" }, { title: "Knives Out" }]
            };
        }
    }
</script>
