// MoviesA/ClientApp/src/app/nav-menu/nav-menu.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../auth/auth.service';

@Component({
  selector: 'app-nav-menu',
  templateUrl: './nav-menu.component.html',
  styleUrls: ['./nav-menu.component.css']
})
export class NavMenuComponent {
  isExpanded = false;

  constructor(public auth: AuthService) {

  };

  collapse() {
    this.isExpanded = false;
  }

  toggle() {
    this.isExpanded = !this.isExpanded;
  }
}

<header>
  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
      <a class="navbar-brand" [routerLink]="['/']">MoviesA</a>
      <button class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target=".navbar-collapse"
              aria-label="Toggle navigation"
              [attr.aria-expanded]="isExpanded"
              (click)="toggle()">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse"
           [ngClass]="{ show: isExpanded }">
        <ul class="navbar-nav flex-grow">
          <li class="nav-item">
            <a class="nav-link text-dark" style="cursor: pointer">{{auth.accessToken}}</a>
          </li>
          <li class="nav-item" *ngIf="!auth.isLoggedIn">
            <a class="nav-link text-dark" (click)="auth.login()" style="cursor: pointer">Login</a>
          </li>
          <li class="nav-item" *ngIf="auth.isLoggedIn">
            <a class="nav-link text-dark" (click)="auth.logout()" style="cursor: pointer">Logout</a>
          </li>
          <li class="nav-item"
              [routerLinkActive]="['link-active']"
              [routerLinkActiveOptions]="{ exact: true }">
            <a class="nav-link text-dark" [routerLink]="['/']">Home</a>
          </li>
          <li class="nav-item" [routerLinkActive]="['link-active']">
            <a class="nav-link text-dark" [routerLink]="['/movies']">Movies</a>
          </li>
          <li class="nav-item" *ngIf="auth.isLoggedIn" [routerLinkActive]="['link-active']">
            <a class="nav-link text-dark" [routerLink]="['/identity']">Identity</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

// MoviesV/src/components/NavMenu.vue
///////////////////////////////////////
//                                   //
//    Author: Max Schwaibold         //
//    Date:   26.05.2020             //
//                                   //
///////////////////////////////////////

<template>
    <header>
        <b-navbar class="border-bottom box-shadow mb-3" toggleable="sm" type="light">
            <b-container>
                <b-navbar-brand to="/">MoviesV</b-navbar-brand>
                <b-navbar-toggle target="menu-links-collapse" class="mr-2" />
                <b-collapse id="menu-links-collapse" class="d-sm-inline-flex flex-sm-row-reverse" is-nav>
                    <ul class="navbar-nav flex-grow">
                        <li class="nav-item" v-show="!$store.state.isAuthenticated">
                            <a class="nav-link text-dark" @click="login()" style="cursor: pointer">Login</a>
                        </li>
                        <li class="nav-item" v-show="$store.state.isAuthenticated">
                            <a class="nav-link text-dark" @click="logout()" style="cursor: pointer">Logout</a>
                        </li>                        
                        <b-nav-item class="text-dark" to="/">Home</b-nav-item>
                        <b-nav-item class="text-dark" to="/movies">Movies</b-nav-item>
                    </ul>
                </b-collapse>
            </b-container>
        </b-navbar>
    </header>    
</template>

<script>
    import { login, logout, isLoggedIn } from '../auth';

    export default {
        created() {
            let store = this.$store;
            isLoggedIn().then(value => {
                if (value) {
                    store.dispatch('login');
                } else {
                    store.dispatch('logout');
                }
            })
        },
        data() {
            return {}
        },
        methods: {
            login,            
            logout
        }        
    }
</script>

<style>
    a.navbar-brand {
        white-space: normal;
        text-align: center;
        word-break: break-all;
    }

    html {
        font-size: 14px;
    }

    @media (min-width: 768px) {
        html {
            font-size: 16px;
        }
    }

    .box-shadow {
        box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05);
    }
</style>
